Repository JECT-Study/JECT-Official-WebSite-Server, pull requests merged in 2025-02, with the labels that each got.

#29 Spring Security 기본 설정 완료
  build.gradle
  src/main/java/org/ject/support/common/security/JwtAccessDeniedHandler.java
  src/main/java/org/ject/support/common/security/JwtAuthenticationEntryPoint.java
  src/main/java/org/ject/support/common/security/JwtAuthenticationFilter.java
  src/main/java/org/ject/support/common/security/JwtTokenProvider.java
  src/main/java/org/ject/support/common/security/SecurityConfig.java
Labels: ⚙️chore

#31 feat: DynamoDB 인터페이스 구현
  .gitignore
  build.gradle
  docker-compose-local.yml
  src/main/java/org/ject/support/common/exception/GlobalErrorCode.java
  src/main/java/org/ject/support/common/util/Json2MapSerializer.java
  src/main/java/org/ject/support/domain/tempapply/domain/TemporaryApplication.java
  src/main/java/org/ject/support/domain/tempapply/repository/TemporaryApplicationRepository.java
  src/main/java/org/ject/support/domain/tempapply/service/TemporaryApplyService.java
  src/main/java/org/ject/support/external/dynamodb/config/AwsDynamoDbConfig.java
  src/main/java/org/ject/support/external/dynamodb/config/DynamoDbInitializer.java
  src/main/java/org/ject/support/external/dynamodb/domain/CompositeKey.java
  src/main/java/org/ject/support/external/dynamodb/domain/EntityWithPrimaryKey.java
  src/main/java/org/ject/support/external/dynamodb/repository/AbstractDynamoDbRepository.java
  src/main/java/org/ject/support/external/dynamodb/repository/DynamoDbRepository.java
  src/main/java/org/ject/support/external/dynamodb/util/CompositeKeyConverter.java
  src/main/java/org/ject/support/external/dynamodb/util/LocalDateTimeConverter.java
  src/main/java/org/ject/support/external/dynamodb/util/MapConverter.java
  src/main/java/org/ject/support/external/email/EmailSendService.java
  src/main/java/org/ject/support/external/email/MailParameter.java
  src/main/resources/application-test.yml
  src/test/java/org/ject/support/common/util/Json2MapSerializerTest.java
  src/test/java/org/ject/support/external/dynamodb/config/DynamoDbInitializerTest.java
  src/test/java/org/ject/support/external/dynamodb/repository/TemporaryApplicationRepositoryTest.java
  src/test/java/org/ject/support/external/email/EmailSendServiceTest.java
Labels: ✨feature, 👨🏻‍💻backend

#36 이메일 인증 및 임시 회원 생성 기능 구현
  src/main/java/org/ject/support/common/data/redis/RedisConfig.java
  src/main/java/org/ject/support/domain/auth/AuthController.java
  src/main/java/org/ject/support/domain/auth/AuthDto.java
  src/main/java/org/ject/support/domain/auth/AuthService.java
  src/main/java/org/ject/support/domain/member/MemberDto.java
  src/main/java/org/ject/support/external/email/EmailController.java
  src/main/java/org/ject/support/external/email/EmailDto.java
  src/main/java/org/ject/support/external/email/EmailSendService.java
  src/main/java/org/ject/support/external/email/MailErrorCode.java
  src/main/java/org/ject/support/external/email/MailException.java
  src/test/java/org/ject/support/domain/auth/AuthServiceTest.java
  src/test/java/org/ject/support/domain/member/MemberTest.java
Labels: ✨feature, 👨🏻‍💻backend

#33 파일 업로드 기능 구현
  build.gradle
  src/main/java/org/ject/support/domain/file/controller/FileController.java
  src/main/java/org/ject/support/domain/file/dto/CreatePresignedUrlResponse.java
  src/main/java/org/ject/support/external/aws/AwsConfig.java
  src/main/java/org/ject/support/external/dynamodb/config/DynamoDbConfig.java
  src/main/java/org/ject/support/external/s3/S3Config.java
  src/main/java/org/ject/support/external/s3/S3Service.java
  src/main/resources/application-test.yml
  src/test/java/org/ject/support/external/s3/S3ServiceTest.java
Labels: ⚙️chore, ✨feature, 👨🏻‍💻backend

#42 프로젝트 목록 조회 기능 구현
  build.gradle
  src/main/java/org/ject/support/domain/member/Team.java
  src/main/java/org/ject/support/domain/member/TeamRepository.java
  src/main/java/org/ject/support/domain/project/controller/ProjectController.java
  src/main/java/org/ject/support/domain/project/dto/ProjectResponse.java
  src/main/java/org/ject/support/domain/project/entity/Project.java
  src/main/java/org/ject/support/domain/project/entity/ProjectIntro.java
  src/main/java/org/ject/support/domain/project/repository/ProjectQueryRepository.java
  src/main/java/org/ject/support/domain/project/repository/ProjectRepository.java
  src/main/java/org/ject/support/domain/project/service/ProjectService.java
  src/main/resources/application-test.yml
  src/test/java/org/ject/support/domain/project/repository/ProjectQueryRepositoryTest.java
Labels: ✨feature, 👨🏻‍💻backend

#49 feat: 서비스 접근 제한기 구현
  build.gradle
  src/main/java/org/ject/support/common/exception/GlobalErrorCode.java
  src/main/java/org/ject/support/common/redis/RedisConfig.java
  src/main/java/org/ject/support/common/schedule/SchedulingConfig.java
  src/main/java/org/ject/support/common/util/PeriodAccessible.java
  src/main/java/org/ject/support/domain/recruit/Recruit.java
  src/main/java/org/ject/support/domain/recruit/domain/ApplicationForm.java
  src/main/java/org/ject/support/domain/recruit/domain/Question.java
  src/main/java/org/ject/support/domain/recruit/domain/Recruit.java
  src/main/java/org/ject/support/domain/recruit/domain/RecruitEntityListener.java
  src/main/java/org/ject/support/domain/recruit/dto/Constants.java
  src/main/java/org/ject/support/domain/recruit/dto/RecruitOpenedEvent.java
  src/main/java/org/ject/support/domain/recruit/exception/RecruitErrorCode.java
  src/main/java/org/ject/support/domain/recruit/exception/RecruitException.java
  src/main/java/org/ject/support/domain/recruit/repository/RecruitQueryRepository.java
  src/main/java/org/ject/support/domain/recruit/repository/RecruitQueryRepositoryImpl.java
  src/main/java/org/ject/support/domain/recruit/repository/RecruitRepository.java
  src/main/java/org/ject/support/domain/recruit/service/AccessPeriodInitializer.java
  src/main/java/org/ject/support/domain/recruit/service/AccessPeriodVerificator.java
  src/main/java/org/ject/support/domain/recruit/service/RecruitScheduleService.java
  src/main/java/org/ject/support/external/dynamodb/config/DynamoDbInitializer.java
  src/main/java/org/ject/support/external/s3/S3Service.java
  src/main/resources/application-test.yml
  src/test/java/org/ject/support/SupportApplicationTests.java
  src/test/java/org/ject/support/domain/file/controller/FileControllerTest.java
  src/test/java/org/ject/support/domain/project/repository/ProjectQueryRepositoryTest.java
  src/test/java/org/ject/support/domain/recruit/service/RecruitScheduleServiceTest.java
  src/test/java/org/ject/support/external/dynamodb/config/DynamoDbInitializerTest.java
  src/test/java/org/ject/support/external/dynamodb/repository/TemporaryApplicationRepositoryTest.java
  src/test/java/org/ject/support/external/email/EmailSendServiceTest.java
  src/test/java/org/ject/support/testconfig/IntegrationTest.java
  src/test/java/org/ject/support/testconfig/MysqlTestContainer.java
  src/test/java/org/ject/support/testconfig/MysqlTestContainersConfig.java
  src/test/java/org/ject/support/testconfig/RedisTestContainersConfig.java
Labels: ✨feature, 👨🏻‍💻backend

#52 프로젝트 상세 조회 기능 구현
  src/main/java/org/ject/support/common/security/CustomUserDetailService.java
  src/main/java/org/ject/support/common/security/CustomUserDetails.java
  src/main/java/org/ject/support/common/security/jwt/JwtTokenProvider.java
  src/main/java/org/ject/support/domain/member/JobFamily.java
  src/main/java/org/ject/support/domain/member/MemberRepository.java
  src/main/java/org/ject/support/domain/member/dto/MemberDto.java
  src/main/java/org/ject/support/domain/member/dto/TeamMemberNames.java
  src/main/java/org/ject/support/domain/member/entity/Member.java
  src/main/java/org/ject/support/domain/member/entity/Team.java
  src/main/java/org/ject/support/domain/member/entity/TeamMember.java
  src/main/java/org/ject/support/domain/member/exception/MemberErrorCode.java
  src/main/java/org/ject/support/domain/member/exception/MemberException.java
  src/main/java/org/ject/support/domain/member/repository/MemberQueryRepository.java
  src/main/java/org/ject/support/domain/member/repository/MemberQueryRepositoryImpl.java
  src/main/java/org/ject/support/domain/member/repository/MemberRepository.java
  src/main/java/org/ject/support/domain/member/repository/TeamMemberRepository.java
  src/main/java/org/ject/support/domain/member/repository/TeamRepository.java
  src/main/java/org/ject/support/domain/project/controller/ProjectController.java
  src/main/java/org/ject/support/domain/project/dto/ProjectDetailResponse.java
  src/main/java/org/ject/support/domain/project/dto/ProjectIntroResponse.java
  src/main/java/org/ject/support/domain/project/entity/Project.java
  src/main/java/org/ject/support/domain/project/entity/ProjectIntro.java
  src/main/java/org/ject/support/domain/project/exception/ProjectErrorCode.java
  src/main/java/org/ject/support/domain/project/exception/ProjectException.java
  src/main/java/org/ject/support/domain/project/repository/ProjectQueryRepository.java
  src/main/java/org/ject/support/domain/project/repository/ProjectQueryRepositoryImpl.java
  src/main/java/org/ject/support/domain/project/repository/ProjectRepository.java
  src/main/java/org/ject/support/domain/project/service/ProjectService.java
  src/main/java/org/ject/support/domain/recruit/domain/ApplicationForm.java
  src/main/resources/application-test.yml
  src/test/java/org/ject/support/common/security/CustomUserDetailServiceTest.java
  src/test/java/org/ject/support/common/security/jwt/JwtTokenProviderTest.java
  src/test/java/org/ject/support/domain/member/MemberTest.java
  src/test/java/org/ject/support/domain/member/repository/MemberQueryRepositoryTest.java
  src/test/java/org/ject/support/domain/project/entity/ProjectIntroTest.java
  src/test/java/org/ject/support/domain/project/repository/ProjectQueryRepositoryTest.java
  src/test/java/org/ject/support/domain/project/service/ProjectServiceTest.java
  src/test/java/org/ject/support/testconfig/QueryDslTestConfig.java
Labels: ✨feature, 👨🏻‍💻backend, 🪄refactor

#56 프로젝트 후기 목록 조회 기능 구현
  src/main/java/org/ject/support/domain/review/Review.java
  src/main/java/org/ject/support/domain/review/controller/ReviewController.java
  src/main/java/org/ject/support/domain/review/dto/ReviewResponse.java
  src/main/java/org/ject/support/domain/review/entity/Review.java
  src/main/java/org/ject/support/domain/review/repository/ReviewQueryRepository.java
  src/main/java/org/ject/support/domain/review/repository/ReviewQueryRepositoryImpl.java
  src/main/java/org/ject/support/domain/review/repository/ReviewRepository.java
  src/main/java/org/ject/support/domain/review/service/ReviewService.java
  src/test/java/org/ject/support/domain/project/repository/ProjectQueryRepositoryTest.java
  src/test/java/org/ject/support/domain/review/repository/ReviewRepositoryTest.java
Labels: ✨feature, 👨🏻‍💻backend

#61 젝톡 목록 조회 기능 구현
  src/main/java/org/ject/support/domain/jectalk/controller/JectalkController.java
  src/main/java/org/ject/support/domain/jectalk/dto/JectalkResponse.java
  src/main/java/org/ject/support/domain/jectalk/entity/Jectalk.java
  src/main/java/org/ject/support/domain/jectalk/repository/JectalkQueryRepository.java
  src/main/java/org/ject/support/domain/jectalk/repository/JectalkQueryRepositoryImpl.java
  src/main/java/org/ject/support/domain/jectalk/repository/JectalkRepository.java
  src/main/java/org/ject/support/domain/jectalk/service/JectalkService.java
  src/test/java/org/ject/support/domain/jectalk/repository/JectalkQueryRepositoryTest.java
Labels: ✨feature, 👨🏻‍💻backend
