Repository JECT-Study/JECT-Official-WebSite-Server, pull requests merged in 2025-08, with the labels that each got.

#236 Slack 메세지 전송 컴포넌트 설정 및 구현
  build.gradle
  src/main/java/org/ject/support/external/slack/SlackComponent.java
  src/main/java/org/ject/support/external/slack/SlackConfig.java
  src/main/resources/application-test.yml
Labels: ⚙️chore, ✨feature, 👨🏻‍💻backend

#245 관리자 로그인 관련 더미 API 추가
  src/main/java/org/ject/support/common/util/CodeGeneratorUtil.java
  src/main/java/org/ject/support/domain/admin/controller/AdminAuthApiSpec.java
  src/main/java/org/ject/support/domain/admin/controller/AdminAuthController.java
  src/main/java/org/ject/support/domain/admin/dto/AdminAuthSendEmailRequest.java
  src/main/java/org/ject/support/domain/admin/dto/AdminAuthSendEmailResponse.java
  src/main/java/org/ject/support/domain/admin/dto/AdminVerifyEmailRequest.java
  src/main/java/org/ject/support/domain/admin/dto/AdminVerifyEmailResponse.java
  src/main/java/org/ject/support/domain/admin/dto/AdminVerifySlackRequest.java
  src/main/java/org/ject/support/external/email/service/EmailAuthService.java
  src/test/java/org/ject/support/common/util/CodeGeneratorUtilTest.java
Labels: ✨feature, 👨🏻‍💻backend, 🪄refactor

#261 swagger GroupedOpenApi에 response 커스터마이저 추가
  src/main/java/org/ject/support/common/springdoc/SpringdocConfig.java
Labels: 🛠️fix

#254 에러 코드 구조 리팩토링
  src/main/java/org/ject/support/common/exception/ErrorCode.java
  src/main/java/org/ject/support/common/exception/GlobalErrorCode.java
  src/main/java/org/ject/support/common/exception/GlobalExceptionHandler.java
  src/main/java/org/ject/support/common/security/jwt/JwtExceptionHandlerFilter.java
  src/main/java/org/ject/support/common/springdoc/ApiErrorResponse.java
  src/main/java/org/ject/support/common/springdoc/ErrorResponseCustomizer.java
  src/main/java/org/ject/support/domain/auth/controller/AuthApiSpec.java
  src/main/java/org/ject/support/domain/auth/exception/AuthErrorCode.java
  src/main/java/org/ject/support/domain/file/controller/FileApiSpec.java
  src/main/java/org/ject/support/domain/file/exception/FileErrorCode.java
  src/main/java/org/ject/support/domain/member/exception/MemberErrorCode.java
  src/main/java/org/ject/support/domain/project/exception/ProjectErrorCode.java
  src/main/java/org/ject/support/domain/project/service/ProjectService.java
  src/main/java/org/ject/support/domain/recruit/exception/ApplyErrorCode.java
  src/main/java/org/ject/support/domain/recruit/exception/QuestionErrorCode.java
  src/main/java/org/ject/support/domain/recruit/exception/RecruitErrorCode.java
  src/main/java/org/ject/support/domain/recruit/exception/SemesterErrorCode.java
  src/main/java/org/ject/support/domain/recruit/service/ApplyService.java
  src/main/java/org/ject/support/domain/recruit/service/RecruitSavedEventHandler.java
  src/main/java/org/ject/support/domain/recruit/service/RecruitService.java
  src/main/java/org/ject/support/domain/recruit/service/RecruitUpdatedEventHandler.java
  src/main/java/org/ject/support/domain/tempapply/exception/TemporaryApplicationErrorCode.java
  src/main/java/org/ject/support/domain/tempapply/service/TemporaryApplyServiceImpl.java
  src/main/java/org/ject/support/external/email/exception/EmailErrorCode.java
  src/test/java/org/ject/support/domain/file/controller/FileControllerTest.java
  src/test/java/org/ject/support/domain/recruit/service/RecruitServiceTest.java
Labels: 🪄refactor

#267 [FEAT] 관리자 로그인 - 2차인증
  src/main/java/org/ject/support/domain/admin/controller/AdminAuthApiSpec.java
  src/main/java/org/ject/support/domain/admin/controller/AdminAuthController.java
  src/main/java/org/ject/support/domain/admin/dto/AdminVerifySlackResponse.java
  src/main/java/org/ject/support/domain/admin/exception/AdminErrorCode.java
  src/main/java/org/ject/support/domain/admin/service/AdminAuthService.java
  src/test/java/org/ject/support/domain/admin/controller/AdminAuthControllerTest.java
  src/test/java/org/ject/support/domain/admin/service/AdminAuthServiceTest.java
Labels: ✨feature, 👨🏻‍💻backend

#270 유효성 검증 실패 응답 포맷 래핑 문제 해결
  src/main/java/org/ject/support/common/exception/GlobalErrorCode.java
  src/main/java/org/ject/support/common/exception/GlobalExceptionHandler.java
  src/main/java/org/ject/support/common/response/ErrorResponse.java
  src/main/java/org/ject/support/common/response/ResponseWrapper.java
  src/main/java/org/ject/support/domain/recruit/controller/RecruitApiSpec.java
  src/main/java/org/ject/support/domain/recruit/controller/RecruitController.java
  src/test/java/org/ject/support/common/security/config/SecurityConfigTest.java
  src/test/java/org/ject/support/domain/auth/AuthControllerTest.java
  src/test/java/org/ject/support/domain/file/controller/FileControllerTest.java
  src/test/java/org/ject/support/domain/recruit/controller/ApplyControllerTest.java
  src/test/java/org/ject/support/domain/recruit/controller/SemesterControllerTest.java
Labels: 🛠️fix
