Repository JECT-Study/JECT-Official-WebSite-Server, pull requests merged in 2025-03, with the labels that each got.

#43 Portfolio 엔티티 구현
  src/main/java/org/ject/support/domain/recruit/Portfolio.java
Labels: ✨feature, 👨🏻‍💻backend

#62 프로젝트 엔티티에 카테고리 컬럼 추가
  src/main/java/org/ject/support/domain/project/controller/ProjectController.java
  src/main/java/org/ject/support/domain/project/entity/Project.java
  src/main/java/org/ject/support/domain/project/repository/ProjectQueryRepository.java
  src/main/java/org/ject/support/domain/project/repository/ProjectQueryRepositoryImpl.java
  src/main/java/org/ject/support/domain/project/service/ProjectService.java
  src/test/java/org/ject/support/domain/project/repository/ProjectQueryRepositoryTest.java
Labels: ✨feature, 👨🏻‍💻backend

#54 feat: 임시 지원서 저장
  build.gradle
  src/main/java/org/ject/support/domain/recruit/controller/ApplyController.java
  src/main/java/org/ject/support/domain/recruit/domain/Question.java
  src/main/java/org/ject/support/domain/recruit/domain/Recruit.java
  src/main/java/org/ject/support/domain/recruit/exception/QuestionErrorCode.java
  src/main/java/org/ject/support/domain/recruit/exception/QuestionException.java
  src/main/java/org/ject/support/domain/recruit/repository/RecruitRepository.java
  src/main/java/org/ject/support/domain/recruit/service/ApplyService.java
  src/main/java/org/ject/support/domain/recruit/service/ApplyUsecase.java
  src/main/java/org/ject/support/domain/tempapply/domain/TemporaryApplication.java
  src/main/java/org/ject/support/domain/tempapply/exception/TemporaryApplicationErrorCode.java
  src/main/java/org/ject/support/domain/tempapply/exception/TemporaryApplicationException.java
  src/main/java/org/ject/support/domain/tempapply/repository/TemporaryApplicationRepository.java
  src/main/java/org/ject/support/domain/tempapply/service/TemporaryApplyService.java
  src/main/java/org/ject/support/domain/tempapply/service/TemporaryApplyServiceImpl.java
  src/test/java/org/ject/support/domain/file/controller/FileControllerTest.java
  src/test/java/org/ject/support/domain/recruit/controller/ApplyControllerTest.java
  src/test/java/org/ject/support/domain/recruit/repository/QuestionRepository.java
  src/test/java/org/ject/support/testconfig/ApplicationPeriodTest.java
  src/test/java/org/ject/support/testconfig/AuthenticatedUser.java
  src/test/java/org/ject/support/testconfig/WithAuthenticatedUserSecurityContextFactory.java
Labels: 👨🏻‍💻backend

#46 이메일 인증 및 임시 회원 생성 기능 구현 완료
  src/main/java/org/ject/support/common/data/redis/RedisConfig.java
  src/main/java/org/ject/support/domain/auth/AuthController.java
  src/main/java/org/ject/support/domain/auth/AuthDto.java
  src/main/java/org/ject/support/domain/auth/AuthErrorCode.java
  src/main/java/org/ject/support/domain/auth/AuthException.java
  src/main/java/org/ject/support/domain/auth/AuthService.java
  src/main/java/org/ject/support/external/email/EmailAuthService.java
  src/main/java/org/ject/support/external/email/EmailController.java
  src/main/java/org/ject/support/external/email/EmailSendService.java
  src/main/java/org/ject/support/external/email/MailErrorCode.java
  src/main/resources/application-test.yml
  src/test/java/org/ject/support/domain/auth/AuthControllerTest.java
  src/test/java/org/ject/support/domain/auth/AuthServiceTest.java
  src/test/java/org/ject/support/domain/file/controller/FileControllerTest.java
  src/test/java/org/ject/support/domain/recruit/controller/ApplyControllerTest.java
  src/test/java/org/ject/support/testconfig/ApplicationPeriodTest.java
  src/test/java/org/ject/support/testconfig/RedisTestContainersConfig.java
Labels: ✨feature, 👨🏻‍💻backend

#65 Role Hierarchy를 사용한 인가 기능 구현
  src/main/java/org/ject/support/common/security/CustomUserDetails.java
  src/main/java/org/ject/support/common/security/config/SecurityConfig.java
  src/main/java/org/ject/support/common/security/jwt/JwtTokenProvider.java
  src/main/java/org/ject/support/domain/auth/AuthController.java
  src/main/java/org/ject/support/external/email/EmailController.java
  src/test/java/org/ject/support/common/security/CustomUserDetailsTest.java
  src/test/java/org/ject/support/common/security/config/SecurityConfigTest.java
  src/test/java/org/ject/support/common/security/jwt/JwtTokenProviderTest.java
  src/test/java/org/ject/support/domain/auth/AuthControllerTest.java
Labels: ✨feature, 👨🏻‍💻backend

#72 CORS 방지를 위한 허용 출처 추가
  src/main/java/org/ject/support/common/security/config/SecurityConfig.java
  src/main/resources/application-test.yml
Labels: 🐛bug, 👨🏻‍💻backend

#73 JwtAuthenticationFilter 로직 수정
  src/main/java/org/ject/support/common/security/jwt/JwtAuthenticationFilter.java
Labels: ✨feature, 👨🏻‍💻backend

#69 권한에 따라 pre-signed url api 분리 및 인가 처리
  src/main/java/org/ject/support/domain/file/controller/FileController.java
  src/main/java/org/ject/support/domain/file/dto/CreatePresignedUrlResponse.java
  src/main/java/org/ject/support/domain/file/dto/UploadFileRequest.java
  src/main/java/org/ject/support/domain/file/dto/UploadFileResponse.java
  src/main/java/org/ject/support/domain/file/exception/FileErrorCode.java
  src/main/java/org/ject/support/domain/file/exception/FileException.java
  src/main/java/org/ject/support/external/s3/S3Service.java
  src/test/java/org/ject/support/domain/file/controller/FileControllerTest.java
  src/test/java/org/ject/support/external/s3/S3ServiceTest.java
Labels: ✨feature, 👨🏻‍💻backend

#90 캐시 적용 및 API 응답 필드 수정
  src/main/java/org/ject/support/common/data/RestPage.java
  src/main/java/org/ject/support/common/data/redis/RedisConfig.java
  src/main/java/org/ject/support/domain/jectalk/controller/JectalkController.java
  src/main/java/org/ject/support/domain/jectalk/dto/JectalkResponse.java
  src/main/java/org/ject/support/domain/jectalk/entity/Jectalk.java
  src/main/java/org/ject/support/domain/jectalk/repository/JectalkQueryRepository.java
  src/main/java/org/ject/support/domain/jectalk/repository/JectalkQueryRepositoryImpl.java
  src/main/java/org/ject/support/domain/jectalk/service/JectalkService.java
  src/main/java/org/ject/support/domain/ministudy/controller/MiniStudyController.java
  src/main/java/org/ject/support/domain/ministudy/dto/MiniStudyResponse.java
  src/main/java/org/ject/support/domain/ministudy/entity/MiniStudy.java
  src/main/java/org/ject/support/domain/ministudy/repository/MiniStudyQueryRepository.java
  src/main/java/org/ject/support/domain/ministudy/repository/MiniStudyQueryRepositoryImpl.java
  src/main/java/org/ject/support/domain/ministudy/service/MiniStudyService.java
  src/main/java/org/ject/support/domain/project/dto/ProjectResponse.java
  src/main/java/org/ject/support/domain/project/repository/ProjectQueryRepository.java
  src/main/java/org/ject/support/domain/project/repository/ProjectQueryRepositoryImpl.java
  src/main/java/org/ject/support/domain/project/service/ProjectService.java
  src/main/java/org/ject/support/domain/review/controller/ReviewController.java
  src/main/java/org/ject/support/domain/review/dto/ReviewResponse.java
  src/main/java/org/ject/support/domain/review/entity/Review.java
  src/main/java/org/ject/support/domain/review/repository/ReviewQueryRepository.java
  src/main/java/org/ject/support/domain/review/repository/ReviewQueryRepositoryImpl.java
  src/main/java/org/ject/support/domain/review/service/ReviewService.java
  src/test/java/org/ject/support/domain/jectalk/repository/JectalkQueryRepositoryTest.java
  src/test/java/org/ject/support/domain/ministudy/repository/MiniStudyQueryRepositoryTest.java
  src/test/java/org/ject/support/domain/project/repository/ProjectQueryRepositoryTest.java
  src/test/java/org/ject/support/domain/review/repository/ReviewRepositoryTest.java
Labels: ⚙️chore, ✨feature, 👨🏻‍💻backend

#99 프로젝트 상세 조회 API 응답 필드명 변경(projectManagers -> productManagers)
  src/main/java/org/ject/support/domain/member/dto/TeamMemberNames.java
  src/test/java/org/ject/support/domain/member/repository/MemberQueryRepositoryTest.java
  src/test/java/org/ject/support/domain/project/service/ProjectServiceTest.java
Labels: 👨🏻‍💻backend, 🪄refactor

#64 feat: 임시 저장 조회
  src/main/java/org/ject/support/domain/recruit/controller/ApplyController.java
  src/main/java/org/ject/support/domain/recruit/service/ApplyService.java
  src/main/java/org/ject/support/domain/recruit/service/ApplyUsecase.java
  src/main/java/org/ject/support/domain/tempapply/domain/TemporaryApplication.java
  src/main/java/org/ject/support/domain/tempapply/repository/TemporaryApplicationRepository.java
  src/main/java/org/ject/support/domain/tempapply/service/TemporaryApplyService.java
  src/main/java/org/ject/support/domain/tempapply/service/TemporaryApplyServiceImpl.java
  src/test/java/org/ject/support/domain/recruit/controller/ApplyControllerTest.java
  src/test/java/org/ject/support/external/dynamodb/repository/TemporaryApplicationRepositoryTest.java
Labels: ✨feature, 👨🏻‍💻backend

#103 지원서 직군 변경 기능 구현
  build.gradle
  src/main/java/org/ject/support/domain/recruit/controller/ApplyController.java
  src/main/java/org/ject/support/domain/recruit/exception/ApplyErrorCode.java
  src/main/java/org/ject/support/domain/recruit/exception/ApplyException.java
  src/main/java/org/ject/support/domain/recruit/service/ApplyService.java
  src/main/java/org/ject/support/domain/recruit/service/ApplyUsecase.java
  src/main/java/org/ject/support/domain/tempapply/repository/TemporaryApplicationRepository.java
  src/main/java/org/ject/support/domain/tempapply/service/TemporaryApplyService.java
  src/main/java/org/ject/support/domain/tempapply/service/TemporaryApplyServiceImpl.java
  src/main/java/org/ject/support/external/dynamodb/repository/AbstractDynamoDbRepository.java
  src/main/java/org/ject/support/external/dynamodb/repository/DynamoDbRepository.java
  src/test/java/org/ject/support/domain/recruit/controller/ApplyControllerTest.java
  src/test/java/org/ject/support/domain/recruit/service/ApplyServiceTest.java
  src/test/java/org/ject/support/external/dynamodb/repository/TemporaryApplicationRepositoryTest.java
Labels: ✨feature, 👨🏻‍💻backend

#105 핀번호 로그인 및 회원 존재 여부 확인 API 구현
  src/main/java/org/ject/support/domain/auth/AuthController.java
  src/main/java/org/ject/support/domain/auth/AuthDto.java
  src/main/java/org/ject/support/domain/auth/AuthErrorCode.java
  src/main/java/org/ject/support/domain/auth/AuthService.java
  src/main/java/org/ject/support/domain/member/repository/MemberRepository.java
  src/test/java/org/ject/support/domain/auth/AuthControllerTest.java
  src/test/java/org/ject/support/domain/auth/AuthServiceTest.java
Labels: ✨feature, 👨🏻‍💻backend

#106 PIN 재설정 기능 구현
  src/main/java/org/ject/support/domain/member/controller/MemberController.java
  src/main/java/org/ject/support/domain/member/dto/MemberDto.java
  src/main/java/org/ject/support/domain/member/entity/Member.java
  src/main/java/org/ject/support/domain/member/exception/MemberErrorCode.java
  src/main/java/org/ject/support/domain/member/service/MemberService.java
  src/test/java/org/ject/support/domain/member/controller/MemberControllerTest.java
  src/test/java/org/ject/support/domain/member/service/MemberServiceTest.java
Labels: ✨feature, 👨🏻‍💻backend

#107 엑세스 토큰 재발급 기능 구현
  src/main/java/org/ject/support/common/exception/GlobalErrorCode.java
  src/main/java/org/ject/support/domain/auth/AuthController.java
  src/main/java/org/ject/support/domain/auth/AuthDto.java
  src/main/java/org/ject/support/domain/auth/AuthErrorCode.java
  src/main/java/org/ject/support/domain/auth/AuthService.java
  src/test/java/org/ject/support/domain/auth/AuthControllerTest.java
  src/test/java/org/ject/support/domain/auth/AuthServiceTest.java
  src/test/java/org/ject/support/domain/file/controller/FileControllerTest.java
  src/test/java/org/ject/support/testconfig/TestSecurityConfig.java
Labels: ✨feature, 👨🏻‍💻backend

#111 Feat/95 reissue access token
  src/main/java/org/ject/support/common/security/CustomSuccessHandler.java
  src/main/java/org/ject/support/common/security/jwt/JwtTokenProvider.java
  src/main/java/org/ject/support/domain/auth/AuthController.java
  src/main/java/org/ject/support/domain/auth/AuthService.java
  src/main/java/org/ject/support/domain/member/service/MemberService.java
  src/test/java/org/ject/support/common/security/jwt/JwtTokenProviderTest.java
  src/test/java/org/ject/support/domain/auth/AuthControllerTest.java
  src/test/java/org/ject/support/domain/auth/AuthServiceTest.java
  src/test/java/org/ject/support/domain/member/service/MemberServiceTest.java
Labels: ✨feature, 👨🏻‍💻backend

#109 지원서 문항 조회 기능 구현
  src/main/java/org/ject/support/domain/recruit/controller/ApplyController.java
  src/main/java/org/ject/support/domain/recruit/controller/QuestionController.java
  src/main/java/org/ject/support/domain/recruit/domain/Question.java
  src/main/java/org/ject/support/domain/recruit/dto/QuestionResponse.java
  src/main/java/org/ject/support/domain/recruit/repository/QuestionQueryRepository.java
  src/main/java/org/ject/support/domain/recruit/repository/QuestionQueryRepositoryImpl.java
  src/main/java/org/ject/support/domain/recruit/repository/QuestionRepository.java
  src/main/java/org/ject/support/domain/recruit/service/QuestionService.java
  src/test/java/org/ject/support/domain/recruit/controller/ApplyControllerTest.java
  src/test/java/org/ject/support/domain/recruit/repository/QuestionQueryRepositoryTest.java
Labels: ✨feature, 👨🏻‍💻backend

#123 chore: refine response wrapper to support only JSON message conversion
  src/main/java/org/ject/support/common/response/ResponseWrapper.java
Labels: 🐛bug, 👨🏻‍💻backend

#129 pre-signed url 발급 완료 시 cdn url 전달하도록 변경
  src/main/java/org/ject/support/domain/file/dto/UploadFileResponse.java
  src/main/java/org/ject/support/external/s3/S3Service.java
  src/test/java/org/ject/support/external/s3/S3ServiceTest.java
Labels: ✨feature, 👨🏻‍💻backend

#132 프로젝트의 기술 스택을 쉼표로 구분하여 조회하도록 구현
  src/main/java/org/ject/support/domain/project/dto/ProjectDetailResponse.java
  src/main/java/org/ject/support/domain/project/entity/Project.java
  src/test/java/org/ject/support/domain/project/service/ProjectServiceTest.java
Labels: ✨feature, 👨🏻‍💻backend

#134 임시 지원서 응답에 직군 추가
  src/main/java/org/ject/support/domain/recruit/dto/ApplyTemporaryResponse.java
  src/main/java/org/ject/support/domain/tempapply/service/TemporaryApplyServiceImpl.java
  src/test/java/org/ject/support/domain/recruit/controller/ApplyControllerTest.java
Labels: ✨feature, 👨🏻‍💻backend

#137 Security 필터 예외처리 수정
  src/main/java/org/ject/support/common/security/jwt/JwtAuthenticationFilter.java
  src/main/java/org/ject/support/common/security/jwt/JwtExceptionHandlerFilter.java
  src/main/java/org/ject/support/domain/member/Role.java
Labels: ✨feature, 👨🏻‍💻backend

#130 API 호출 시 발생 가능한 예외 처리
  src/main/java/org/ject/support/common/exception/GlobalErrorCode.java
  src/main/java/org/ject/support/common/exception/GlobalExceptionHandler.java
  src/test/java/org/ject/support/common/security/config/SecurityConfigTest.java
  src/test/java/org/ject/support/domain/auth/AuthControllerTest.java
Labels: ✨feature, 👨🏻‍💻backend

#126 페이지 응답 포맷 변경
  scripts/start.sh
  src/main/java/org/ject/support/common/data/PageResponse.java
  src/main/java/org/ject/support/common/data/RestPage.java
  src/main/java/org/ject/support/domain/jectalk/controller/JectalkController.java
  src/main/java/org/ject/support/domain/jectalk/repository/JectalkQueryRepository.java
  src/main/java/org/ject/support/domain/jectalk/repository/JectalkQueryRepositoryImpl.java
  src/main/java/org/ject/support/domain/jectalk/service/JectalkService.java
  src/main/java/org/ject/support/domain/ministudy/controller/MiniStudyController.java
  src/main/java/org/ject/support/domain/ministudy/repository/MiniStudyQueryRepository.java
  src/main/java/org/ject/support/domain/ministudy/repository/MiniStudyQueryRepositoryImpl.java
  src/main/java/org/ject/support/domain/ministudy/service/MiniStudyService.java
  src/main/java/org/ject/support/domain/project/controller/ProjectController.java
  src/main/java/org/ject/support/domain/project/repository/ProjectQueryRepository.java
  src/main/java/org/ject/support/domain/project/repository/ProjectQueryRepositoryImpl.java
  src/main/java/org/ject/support/domain/project/service/ProjectService.java
  src/main/java/org/ject/support/domain/review/controller/ReviewController.java
  src/main/java/org/ject/support/domain/review/repository/ReviewQueryRepository.java
  src/main/java/org/ject/support/domain/review/repository/ReviewQueryRepositoryImpl.java
  src/main/java/org/ject/support/domain/review/service/ReviewService.java
Labels: ⚙️chore, 👨🏻‍💻backend, 🪄refactor

#142 모니터링 툴 사용을 위한 actuator, prometheus 의존성 추가
  build.gradle
Labels: ⚙️chore, 👨🏻‍💻backend

#148 cloudfront domain @Value 누락된 접두사 추가
  src/main/java/org/ject/support/external/s3/S3Service.java
  src/main/resources/application-test.yml
Labels: ⚙️chore, 👨🏻‍💻backend, 🪄refactor

#150 Recruit의 기간 필드의 타입을 LocalDateTime으로 변경
  src/main/java/org/ject/support/domain/recruit/domain/Recruit.java
  src/main/java/org/ject/support/domain/recruit/repository/QuestionQueryRepository.java
  src/main/java/org/ject/support/domain/recruit/repository/QuestionQueryRepositoryImpl.java
  src/main/java/org/ject/support/domain/recruit/repository/RecruitQueryRepository.java
  src/main/java/org/ject/support/domain/recruit/repository/RecruitQueryRepositoryImpl.java
  src/main/java/org/ject/support/domain/recruit/repository/RecruitRepository.java
  src/main/java/org/ject/support/domain/recruit/service/AccessPeriodInitializer.java
  src/main/java/org/ject/support/domain/recruit/service/ApplyService.java
  src/main/java/org/ject/support/domain/recruit/service/QuestionService.java
  src/main/java/org/ject/support/domain/recruit/service/RecruitScheduleService.java
  src/test/java/org/ject/support/domain/file/controller/FileControllerTest.java
  src/test/java/org/ject/support/domain/recruit/controller/ApplyControllerTest.java
  src/test/java/org/ject/support/domain/recruit/domain/RecruitTest.java
  src/test/java/org/ject/support/domain/recruit/repository/QuestionQueryRepositoryTest.java
  src/test/java/org/ject/support/domain/recruit/service/RecruitScheduleServiceTest.java
Labels: 👨🏻‍💻backend, 🪄refactor
