Repository JECT-Study/JECT-Official-WebSite-Server, pull requests merged in 2025-04, with the labels that each got.

#152 지원서 문항 조회 기능에 캐싱 적용
  src/main/java/org/ject/support/common/data/redis/RedisConfig.java
  src/main/java/org/ject/support/domain/recruit/service/QuestionService.java
  src/test/java/org/ject/support/domain/recruit/controller/QuestionControllerTest.java
Labels: ✨feature, 👨🏻‍💻backend

#157 핀 재설정 시 이메일 발송 및 인증 번호 검증 기능 구현
  src/main/java/org/ject/support/domain/auth/AuthController.java
  src/main/java/org/ject/support/domain/auth/AuthDto.java
  src/main/java/org/ject/support/domain/auth/AuthService.java
  src/main/java/org/ject/support/external/email/EmailAuthService.java
  src/main/java/org/ject/support/external/email/EmailController.java
  src/main/java/org/ject/support/external/email/EmailTemplate.java
  src/test/java/org/ject/support/domain/auth/AuthControllerTest.java
  src/test/java/org/ject/support/domain/auth/AuthServiceTest.java
Labels: ✨feature, 👨🏻‍💻backend

#159 Feat/156 reset pin send email
  src/main/java/org/ject/support/domain/auth/AuthDto.java
Labels: ⚙️chore, 👨🏻‍💻backend

#161 직군 변경 API 제거 및 임시 지원서 제거 기능 구현
  src/main/java/org/ject/support/domain/recruit/controller/ApplyController.java
  src/main/java/org/ject/support/domain/recruit/service/ApplyService.java
  src/main/java/org/ject/support/domain/recruit/service/ApplyUsecase.java
  src/test/java/org/ject/support/domain/recruit/controller/ApplyControllerTest.java
  src/test/java/org/ject/support/domain/recruit/service/ApplyServiceTest.java
Labels: ✨feature, 👨🏻‍💻backend

#163 SELECT 타입 문항을 제공할 수 있도록 구현
  src/main/java/org/ject/support/common/util/StringListConverter.java
  src/main/java/org/ject/support/domain/project/entity/Project.java
  src/main/java/org/ject/support/domain/recruit/domain/Question.java
  src/main/java/org/ject/support/domain/recruit/dto/QuestionResponse.java
  src/main/java/org/ject/support/domain/recruit/repository/QuestionQueryRepositoryImpl.java
  src/test/java/org/ject/support/domain/project/repository/ProjectQueryRepositoryTest.java
  src/test/java/org/ject/support/domain/project/service/ProjectServiceTest.java
  src/test/java/org/ject/support/domain/recruit/controller/ApplyControllerTest.java
  src/test/java/org/ject/support/domain/recruit/controller/QuestionControllerTest.java
  src/test/java/org/ject/support/domain/recruit/repository/QuestionQueryRepositoryTest.java
Labels: ✨feature, 👨🏻‍💻backend, 🪄refactor

#170 캐시 키에 pageable size 포함
  src/main/java/org/ject/support/domain/jectalk/service/JectalkService.java
  src/main/java/org/ject/support/domain/ministudy/service/MiniStudyService.java
  src/main/java/org/ject/support/domain/project/service/ProjectService.java
  src/main/java/org/ject/support/domain/review/service/ReviewService.java
Labels: 👨🏻‍💻backend, 🛠️fix

#164 이메일 단건 발송 시 가상 스레드 적용
  build.gradle
  src/main/java/org/ject/support/SupportApplication.java
  src/main/java/org/ject/support/external/email/EmailSendService.java
  src/main/java/org/ject/support/external/email/event/EmailSendEvent.java
  src/main/java/org/ject/support/external/email/event/EmailSendEventListener.java
  src/main/resources/application-test.yml
  src/test/java/org/ject/support/external/email/EmailSendServiceTest.java
Labels: ✨feature, 👨🏻‍💻backend

#172 Logback + CloudWatch 세팅
  build.gradle
  src/main/resources/application-test.yml
  src/main/resources/logs/logback-local.xml
  src/main/resources/logs/logback-prod.xml
Labels: ⚙️chore, 👨🏻‍💻backend

#169 쿠키 발급 시 setSecure 설정 활성화
  src/main/java/org/ject/support/common/security/jwt/JwtCookieProvider.java
Labels: ✨feature, 👨🏻‍💻backend

#173 쿠키 발급받는 도메인 설정
  src/main/java/org/ject/support/common/security/config/SecurityConfig.java
  src/main/java/org/ject/support/common/security/jwt/JwtCookieProvider.java
  src/main/resources/application-test.yml
Labels: ✨feature, 👨🏻‍💻backend

#177 Feat/inhance converters null safety
  src/main/java/org/ject/support/common/util/StringListConverter.java
  src/test/java/org/ject/support/common/util/StringListConverterTest.java
Labels: 🐛bug, 👨🏻‍💻backend

#178 토큰을 쿠키에서 가져오도록 인증 로직 수정
  src/main/java/org/ject/support/common/security/CustomSuccessHandler.java
  src/main/java/org/ject/support/common/security/jwt/JwtAuthenticationFilter.java
  src/main/java/org/ject/support/common/security/jwt/JwtCookieProvider.java
  src/main/java/org/ject/support/common/security/jwt/JwtTokenProvider.java
  src/main/java/org/ject/support/domain/auth/AuthController.java
  src/main/java/org/ject/support/domain/auth/AuthService.java
  src/main/java/org/ject/support/domain/auth/AuthVerificationResult.java
  src/main/java/org/ject/support/external/email/MailErrorCode.java
  src/test/java/org/ject/support/common/security/jwt/JwtTokenProviderTest.java
  src/test/java/org/ject/support/domain/auth/AuthControllerTest.java
  src/test/java/org/ject/support/domain/auth/AuthServiceTest.java
Labels: ✨feature, 👨🏻‍💻backend

#180 쿠키 발급 로직 수정
  src/main/java/org/ject/support/common/security/jwt/JwtTokenProvider.java
  src/main/java/org/ject/support/domain/auth/AuthService.java
  src/main/java/org/ject/support/domain/member/controller/MemberController.java
  src/main/java/org/ject/support/domain/member/service/MemberService.java
  src/test/java/org/ject/support/domain/auth/AuthControllerTest.java
  src/test/java/org/ject/support/domain/auth/AuthServiceTest.java
  src/test/java/org/ject/support/domain/member/controller/MemberControllerTest.java
  src/test/java/org/ject/support/domain/member/service/MemberServiceTest.java
Labels: ✨feature, 👨🏻‍💻backend

#184 인증 API 호출 완료 시 클라이언트에 명시적인 응답 반환
  src/main/java/org/ject/support/domain/auth/AuthController.java
  src/main/java/org/ject/support/domain/auth/AuthDto.java
  src/main/java/org/ject/support/domain/member/controller/MemberController.java
  src/main/java/org/ject/support/domain/member/dto/MemberDto.java
  src/test/java/org/ject/support/domain/auth/AuthServiceTest.java
Labels: ✨feature, 👨🏻‍💻backend

#186 기수 목록 조회 시 redis 역직렬화 이슈 해결
  src/main/java/org/ject/support/domain/recruit/controller/QuestionController.java
  src/main/java/org/ject/support/domain/recruit/controller/SemesterController.java
  src/main/java/org/ject/support/domain/recruit/dto/QuestionResponses.java
  src/main/java/org/ject/support/domain/recruit/dto/SemesterResponse.java
  src/main/java/org/ject/support/domain/recruit/dto/SemesterResponses.java
  src/main/java/org/ject/support/domain/recruit/service/QuestionService.java
  src/main/java/org/ject/support/domain/recruit/service/SemesterInquiryService.java
  src/main/java/org/ject/support/domain/recruit/service/SemesterInquiryUsecase.java
Labels: 👨🏻‍💻backend, 🛠️fix

#185 인증 코드 이메일 템플릿 수정
  src/main/java/org/ject/support/domain/auth/AuthService.java
  src/main/java/org/ject/support/domain/auth/AuthVerificationResult.java
  src/main/java/org/ject/support/external/email/EmailTemplate.java
  src/main/resources/templates/email-template.html
  src/test/java/org/ject/support/domain/auth/AuthControllerTest.java
  src/test/java/org/ject/support/domain/auth/AuthServiceTest.java
Labels: ✨feature, 👨🏻‍💻backend

#189 recruit flag 관리 로직 개선
  src/main/java/org/ject/support/common/exception/GlobalErrorCode.java
  src/main/java/org/ject/support/common/util/PeriodAccessible.java
  src/main/java/org/ject/support/domain/recruit/domain/Recruit.java
  src/main/java/org/ject/support/domain/recruit/domain/RecruitEntityListener.java
  src/main/java/org/ject/support/domain/recruit/dto/Constants.java
  src/main/java/org/ject/support/domain/recruit/dto/RecruitOpenedEvent.java
  src/main/java/org/ject/support/domain/recruit/dto/RecruitRegisterRequest.java
  src/main/java/org/ject/support/domain/recruit/dto/RecruitSavedEvent.java
  src/main/java/org/ject/support/domain/recruit/dto/RecruitUpdateRequest.java
  src/main/java/org/ject/support/domain/recruit/repository/RecruitQueryRepository.java
  src/main/java/org/ject/support/domain/recruit/repository/RecruitQueryRepositoryImpl.java
  src/main/java/org/ject/support/domain/recruit/repository/RecruitRepository.java
  src/main/java/org/ject/support/domain/recruit/service/AccessPeriodInitializer.java
  src/main/java/org/ject/support/domain/recruit/service/AccessPeriodVerificator.java
  src/main/java/org/ject/support/domain/recruit/service/AccessPeriodVerifier.java
  src/main/java/org/ject/support/domain/recruit/service/ApplyService.java
  src/main/java/org/ject/support/domain/recruit/service/RecruitFlagService.java
  src/main/java/org/ject/support/domain/recruit/service/RecruitSavedEventHandler.java
  src/main/java/org/ject/support/domain/recruit/service/RecruitScheduleService.java
  src/main/java/org/ject/support/external/s3/S3Service.java
  src/test/java/org/ject/support/domain/file/controller/FileControllerTest.java
  src/test/java/org/ject/support/domain/recruit/controller/QuestionControllerTest.java
  src/test/java/org/ject/support/domain/recruit/service/AccessPeriodInitializerTest.java
  src/test/java/org/ject/support/domain/recruit/service/AccessPeriodVerifierTest.java
  src/test/java/org/ject/support/domain/recruit/service/RecruitFlagServiceTest.java
  src/test/java/org/ject/support/domain/recruit/service/RecruitSavedEventHandlerTest.java
  src/test/java/org/ject/support/domain/recruit/service/RecruitScheduleServiceTest.java
  src/test/java/org/ject/support/domain/recruit/service/RecruitServiceTest.java
  src/test/java/org/ject/support/testconfig/ApplicationPeriodTest.java
Labels: 👨🏻‍💻backend, 🪄refactor

#196 chore: blue green
  scripts/before_install.sh
Labels: ⚙️chore, 👨🏻‍💻backend

#203 핀번호 수정 시 이전과 동일한 핀번호도 허용하도록 수정
  src/main/java/org/ject/support/domain/member/exception/MemberErrorCode.java
  src/main/java/org/ject/support/domain/member/service/MemberService.java
  src/test/java/org/ject/support/domain/member/controller/MemberControllerTest.java
  src/test/java/org/ject/support/domain/member/service/MemberServiceTest.java
Labels: ✨feature, 👨🏻‍💻backend

#206 프로젝트 목록 조회 시 id 내림차순 정렬 조건 추가
  src/main/java/org/ject/support/domain/project/repository/ProjectQueryRepositoryImpl.java
  src/test/java/org/ject/support/domain/project/repository/ProjectQueryRepositoryTest.java
Labels: ✨feature, 👨🏻‍💻backend

#208 지원서 제출 상태 확인 기능 구현
  src/main/java/org/ject/support/domain/recruit/controller/ApplyController.java
  src/main/java/org/ject/support/domain/recruit/repository/ApplicationFormRepository.java
  src/main/java/org/ject/support/domain/recruit/service/ApplyService.java
  src/main/java/org/ject/support/domain/recruit/service/ApplyUsecase.java
  src/test/java/org/ject/support/domain/recruit/controller/ApplyControllerTest.java
  src/test/java/org/ject/support/domain/recruit/repository/ApplicationFormRepositoryTest.java
Labels: ✨feature, 👨🏻‍💻backend

#210 Feat/209 pin email template
  src/main/java/org/ject/support/external/email/EmailTemplate.java
  src/main/resources/templates/auth-code-email-template.html
  src/main/resources/templates/pin-reset-email-template.html
  src/test/java/org/ject/support/external/email/EmailSendServiceTest.java
Labels: ✨feature, 👨🏻‍💻backend

#212 Feat/211 check member inform api
  src/main/java/org/ject/support/domain/member/controller/MemberController.java
  src/main/java/org/ject/support/domain/member/entity/Member.java
  src/main/java/org/ject/support/domain/member/service/MemberService.java
  src/test/java/org/ject/support/domain/member/controller/MemberControllerTest.java
Labels: ✨feature, 👨🏻‍💻backend

#214 Spring Boot 타임존 Asia/Seoul 설정
  src/main/java/org/ject/support/SupportApplication.java
Labels: ✨feature, 👨🏻‍💻backend

#216 이메일 발송 서버를 Amazon SES로 마이그레이션
  build.gradle
  src/main/java/org/ject/support/domain/auth/AuthController.java
  src/main/java/org/ject/support/domain/auth/AuthService.java
  src/main/java/org/ject/support/external/email/EmailConfig.java
  src/main/java/org/ject/support/external/email/EmailSendService.java
  src/main/java/org/ject/support/external/email/MailErrorCode.java
  src/main/java/org/ject/support/external/email/MailSendException.java
  src/main/java/org/ject/support/external/email/MessageGenerator.java
  src/main/java/org/ject/support/external/email/config/SesConfig.java
  src/main/java/org/ject/support/external/email/controller/EmailAuthController.java
  src/main/java/org/ject/support/external/email/domain/EmailTemplate.java
  src/main/java/org/ject/support/external/email/event/EmailSendEvent.java
  src/main/java/org/ject/support/external/email/event/EmailSendEventListener.java
  src/main/java/org/ject/support/external/email/exception/EmailErrorCode.java
  src/main/java/org/ject/support/external/email/exception/EmailException.java
  src/main/java/org/ject/support/external/email/service/EmailAuthService.java
  src/main/java/org/ject/support/external/email/service/EmailSendService.java
  src/main/resources/application-test.yml
  src/main/resources/templates/auth-code-email-template.html
  src/main/resources/templates/pin-reset-email-template.html
  src/test/java/org/ject/support/domain/auth/AuthControllerTest.java
  src/test/java/org/ject/support/domain/auth/AuthServiceTest.java
  src/test/java/org/ject/support/external/email/EmailSendServiceTest.java
Labels: 👨🏻‍💻backend, 🪄refactor

#218 요청, 응답 로그 분리 및 http 메서드와 응답 시간 추가
  src/main/java/org/ject/support/common/security/jwt/JwtExceptionHandlerFilter.java
Labels: ⚙️chore, 👨🏻‍💻backend
